152 session manager component
joshherkness/AR-Top pull request #186
Opened 2018-02-18 01:56 UTC by kdjohnson

closes #152

2018-02-18 17:06 UTC, joshherkness commented on vue/src/components/SessionManager.vue
> +      const mapID = store.state.session.session.session.game_map_id.$oid
Um..... let's try to fix this repetition.

2018-02-18 17:08 UTC, joshherkness commented on vue/src/components/SessionManager.vue
> +      // TODO: emit to party
This won't emit the map to the party, but rather just send out a request to the API to update the session, setting the map of the session to the new map.

2018-02-18 17:10 UTC, joshherkness commented on vue/src/components/SessionModal.vue
> +          <article class="message is-warning">
Try moving this from an is-warning to an is-info, or removing the message bounds all together into just a paragraph element. I don't know if a warning message is necessary, and my eyes were immediately drawn to it on modal open.

2018-02-18 17:22 UTC, joshherkness requested changes

2018-02-18 17:22 UTC, joshherkness commented on vue/src/components/SessionModal.vue
> +    },
We don't need `beforeOpened` and `beforeClosed` on this modal, since it isn't currently accepting any parameters on modal open.

2018-02-18 19:40 UTC, joshherkness commented
Now that I think of it, putting the session manager bar at the bottom of the page, with a dark background might look really cool. It would require a bit of a rework to the current layout of our page though (buttons on the editor would be covered by the session manager bar).

2018-02-18 22:36 UTC, kdjohnson commented
<img width="1440" alt="screen shot 2018-02-18 at 5 36 21 pm" src="https://user-images.githubusercontent.com/11354738/36357866-4a3985ee-14d2-11e8-87ca-28b146be7519.png">

2018-02-19 00:47 UTC, joshherkness commented
What do you think?

2018-02-19 01:01 UTC, kdjohnson commented
I think it's a good idea.

2018-02-19 01:02 UTC, joshherkness commented
The buttons need a bit of theme work...

2018-02-19 01:06 UTC, kdjohnson commented
<img width="1440" alt="screen shot 2018-02-18 at 8 05 44 pm" src="https://user-images.githubusercontent.com/11354738/36359259-239730ac-14e7-11e8-84b5-31c73ee1f9cb.png">

2018-02-19 01:10 UTC, joshherkness commented
Try white background with dark text instead of the blue

2018-02-19 01:24 UTC, kdjohnson commented
<img width="1440" alt="screen shot 2018-02-18 at 8 24 36 pm" src="https://user-images.githubusercontent.com/11354738/36359475-c34bd006-14e9-11e8-8b3f-6e62bc83e293.png">

2018-02-19 01:51 UTC, joshherkness commented
I like that more. What about you?  What could we do with the tags?  White text "Invitation code" with whit
e background dark  text code?

2018-02-19 02:06 UTC, kdjohnson commented
I prefer this one over the previous ones. 
<img width="1440" alt="screen shot 2018-02-18 at 9 04 42 pm" src="https://user-images.githubusercontent.com/11354738/36360164-69d95de4-14ef-11e8-971e-1780e5133f18.png">

2018-02-19 02:09 UTC, kdjohnson commented
Here is what it looks like in the editor

2018-02-19 02:28 UTC, joshherkness commented
I like that too. Picture of it inside the editor?

2018-02-19 02:38 UTC, kdjohnson commented
I just meant with the whole page being shown in the screenshot.

2018-02-19 02:40 UTC, joshherkness commented
I don't see the image.

2018-02-19 02:41 UTC, kdjohnson commented
<img width="1440" alt="screen shot 2018-02-18 at 9 08 47 pm" src="https://user-images.githubusercontent.com/11354738/36360231-f66d3b90-14ef-11e8-8e2c-e2ad0b78557b.png">

2018-02-19 02:41 UTC, joshherkness commented
I like it

2018-02-21 04:19 UTC, joshherkness commented
Fixed bug where editor was not updating, however loading is now somewhat broken. You'll notice a latency when you open the editor through any means. This is because I'm now loading the map (the network request) as soon as you route, thus before the component mounts. Because of this, the component appears as if there is a latency from the user click. I'll look into this, but if you have any ideas, they are welcome.

2018-02-21 04:33 UTC, joshherkness commented
Wait, i got it

2018-02-22 00:47 UTC, joshherkness commented
So, I began implementing the map change functionality for a session, however the update_session api endpoint is not returning me the new game_map_id like the create_session endpoint is.

2018-02-22 00:47 UTC, joshherkness commented
Also, I don't think the set height is good for the  lists, because whitespace starts showing up on taller displays.

2018-02-22 00:53 UTC, joshherkness commented
I think it stems from the fact that I'm passing a string value in for the game_map_id, and it is trying to store it inside of a ObjectIDField, which it cannot.

2018-02-22 00:54 UTC, joshherkness commented
I'm not sure

2018-02-22 01:24 UTC, joshherkness commented
Wait, I fixed it

2018-02-22 01:30 UTC, kdjohnson commented
`Also, I don't think the set height is good for the  lists, because whitespace starts showing up on taller displays. `

What is this referring to?

2018-02-22 01:31 UTC, joshherkness commented
The commit that adds scrolling to the list (6d1818c)

2018-02-22 01:31 UTC, joshherkness commented
<img width="908" alt="screen shot 2018-02-21 at 8 31 23 pm" src="https://user-images.githubusercontent.com/5797470/36515218-3b1bd85c-1746-11e8-9c38-f811f2b23e02.png">

Lots of whitespace

2018-02-22 01:38 UTC, kdjohnson commented
OK. I just set it arbitrarily. I figured we'd fine tune it at some point.

2018-02-22 01:43 UTC, joshherkness commented
It might be better just to not have it for now, rather than have it look buggy. We can add it in next sprint. Does that sound alright to you?

2018-02-22 01:54 UTC, joshherkness commented
Also, I think this is good to merge in, what do you think?

2018-02-22 02:16 UTC, kdjohnson commented
What does it look like if you increase `max-height`?

2018-02-22 02:21 UTC, joshherkness commented
It would fix it, but only if I tweak it to my screen size.

2018-02-22 02:23 UTC, joshherkness commented
I want to look into making custom flex to do it.

2018-02-22 02:38 UTC, kdjohnson commented
take it out if you want.

2018-02-22 02:40 UTC, joshherkness commented
Also, table columns on the map list are broken (not aligned with the body)

2018-02-22 02:44 UTC, kdjohnson commented
I had noticed that and had a fix for it,  but since we not gonna use it then it won't matter.

2018-02-22 02:46 UTC, joshherkness commented
Im sorry!

2018-02-22 02:47 UTC, kdjohnson commented
np, I'm sure your implementation will be better/cleaner.

2018-02-22 02:49 UTC, joshherkness commented
Honestly, I hate working on tables. That is what I did at my last two internships...

2018-02-22 02:51 UTC, joshherkness commented
Play around with this branch and let me know if we can merge it in.

2018-02-22 03:02 UTC, kdjohnson commented on .tern-port
> +65360
Probably want to remove this no?

2018-02-22 03:02 UTC, kdjohnson commented on server/api.py
> +            current_app.logger.debug(session_id)
Can we remove this?

2018-02-22 03:07 UTC, joshherkness commented on server/api.py
> +            current_app.logger.debug(session_id)
The debug? Ya, I can do that

2018-02-22 03:09 UTC, joshherkness commented on .tern-port
> +65360
Ya, I thought this was git ignored...

2018-02-22 03:23 UTC, kdjohnson commented
https://github.com/joshherkness/AR-Top/blob/11a41b530e82c2e90b1749b41c3c3ea881f566e8/server/models.py#L144

Once it is set it cannot be updated currently.

2018-02-22 03:24 UTC, joshherkness commented
We don't want the code to be able to change, right?

2018-02-22 03:25 UTC, kdjohnson commented
I thought we did. If that's not the case then. I think this ready to be merged in.

2018-02-22 03:26 UTC, joshherkness approved these changes

2018-02-22 03:26 UTC, merged