230 retrieve session on authentication
joshherkness/AR-Top pull request #231
Opened 2018-03-08 00:07 UTC by joshherkness

Retrieve any current sessions for a user upon successful authentication.

2018-03-08 23:39 UTC, kdjohnson requested changes

2018-03-08 23:39 UTC, kdjohnson commented on vue/src/components/Authentication.vue
> +        }).catch((err) => {
Have eslint ignore this line.

2018-03-08 23:59 UTC, joshherkness commented
There we go.

2018-03-09 02:13 UTC, kdjohnson approved these changes

2018-03-09 17:28 UTC, kdjohnson commented
@jjrobertson14 Have you tried this?

2018-03-09 17:44 UTC, jjrobertson14 approved these changes
The changes to tests.py and server.py look fine, and the tests for read_session_user_id still pass

2018-03-09 18:00 UTC, merged