Implement entity models
joshherkness/AR-Top pull request #261
Opened 2018-03-18 02:56 UTC by joshherkness

- closes #256
- closes #257
- closes #258 
- closes #259 
- closes #260

2018-03-18 02:56 UTC, joshherkness commented
Most of these file additions are simply the raw model data. No way to compress this,

2018-03-19 19:39 UTC, kdjohnson commented
I'll look at this either later tonight or definitely tomorrow.

2018-03-21 16:06 UTC, kdjohnson requested changes

2018-03-21 16:06 UTC, kdjohnson commented on docker-compose.yml
> +            - "27017:2017"
This needs to be changed back to `"27017:27017"`

2018-03-21 16:06 UTC, kdjohnson commented on vue/config/index.js
> +    port: 3000, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
Why was this port changed?

2018-03-21 19:57 UTC, kdjohnson approved these changes

2018-03-21 19:58 UTC, merged